# Generated by Django 5.2.3 on 2026-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_token_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('token_admin', 'Token Admin'), ('patient', 'Patient'), ('ambulance', 'Ambulance')], default='patient', max_length=20),
        ),
    ]
