# Generated by Django 5.2.3 on 2026-07-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalConfig',
        ),
    ]
